### PR TITLE
Command line arguments

### PR DESCRIPTION
**Pull request by gabi-250**
This branch contains the following new features:
- better command-line arguments for the player
- a text-based terminal player, which can be used by running the program with the `--no-gui` option

### CODE REVIEW

**Comment by rbartlensky** [comment]
There is a bug when I want to add a new file and I'm specifying a relative path. An `IOError` gets raised if I'm in `--no-gui` mode and I choose to add a song by specifying a relative path: `a ~/path/to/song.mp3`. If I provide an absolute path everything works just fine. This can be fixed in another PR and I will create an issue.

**Comment by gabi-250** [comment]
Can I squash then?

**Comment by rbartlensky** [comment]
Yes, you can.

**Comment by gabi-250** [comment]
Done.

**Pull request merged**
